version: '3.1'
volumes:
  message_queue_volume: null
  test_db_volume: null
services:
  api:
    build: ./api
    environment: 
      AMQP_ADDRESS: 'amqp://message-queue:5672'
      PORT: 3000
    expose:
      - '3000'
    links:
      - message-queue
  message-queue:
    image: 'rabbitmq:3.6-management'
    expose:
      - 5672
      - 15672
    ports:
      - 15672
    environment:
      CONFD_ARGS: '--interval 5'
      RABBITMQ_CLUSTER_PARTITION_HANDLING: autoheal
      RABBITMQ_NET_TICKTIME: '60'
      RABBITMQ_ERLANG_COOKIE: message-queue-cookie
      RABBITMQ_NODENAME: rabbitmqnode@localhost
    volumes:
      - 'message_queue_volume:/var/lib/rabbitmq'
  server:
    build: ./front-end
    environment:
      NODE_ENV: 'debug'
      API_PORT: '3000'
    ports:
      - '80:80'
      - '433:433'
    links:
      - api
  test_db:
    image: 'postgres:11'
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test_db
    ports:
      - '5432:5432'
    volumes:
      - 'test_db_volume:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      